// webui/src/routes/ConfigTab.svelte
<script lang="ts">
  import { store } from '../lib/store.svelte';
  import { ICONS } from '../lib/constants';
  import ChipInput from '../components/ChipInput.svelte';
  import BottomActions from '../components/BottomActions.svelte';
  import { slide } from 'svelte/transition';
  import './ConfigTab.css';
  import '@material/web/textfield/outlined-text-field.js';
  import '@material/web/button/filled-button.js';
  import '@material/web/iconbutton/filled-tonal-icon-button.js';
  import '@material/web/iconbutton/icon-button.js';
  import '@material/web/icon/icon.js';
  import '@material/web/ripple/ripple.js';
  import '@material/web/dialog/dialog.js';
  import '@material/web/button/text-button.js';

  let initialConfigStr = $state('');
  let showResetConfirm = $state(false);

  const isValidPath = (p: string) => !p || (p.startsWith('/') && p.length > 1);
  let invalidModuleDir = $derived(!isValidPath(store.config.moduledir));
  let invalidTempDir = $derived(store.config.tempdir && !isValidPath(store.config.tempdir));
  let isDirty = $derived.by(() => {
    if (!initialConfigStr) return false;
    return JSON.stringify(store.config) !== initialConfigStr;
  });

  $effect(() => {
    if (!store.loading.config && store.config) {
      if (!initialConfigStr || initialConfigStr === JSON.stringify(store.config)) {
        initialConfigStr = JSON.stringify(store.config);
      }
    }
  });

  $effect(() => {
    if (store.systemInfo?.zygisksuEnforce && store.systemInfo.zygisksuEnforce !== '0' && !store.config.allow_umount_coexistence) {
        if (!store.config.disable_umount) {
            store.config.disable_umount = true;
        }
    }
  });

  function save() {
    if (invalidModuleDir || invalidTempDir) {
      store.showToast(store.L.config.invalidPath, "error");
      return;
    }
    store.saveConfig().then(() => {
        initialConfigStr = JSON.stringify(store.config);
    });
  }

  function reload() {
    store.loadConfig().then(() => {
        initialConfigStr = JSON.stringify(store.config);
    });
  }
  
  function reset() {
    showResetConfirm = false;
    store.resetConfig().then(() => {
        initialConfigStr = JSON.stringify(store.config);
    });
  }

  function resetTempDir() {
    store.config.tempdir = "";
  }

  function toggle(key: keyof typeof store.config) {
    if (key === 'disable_umount') {
       if (store.systemInfo?.zygisksuEnforce && store.systemInfo.zygisksuEnforce !== '0' && !store.config.allow_umount_coexistence) {
          store.showToast(store.L.config?.coexistenceRequired || "Coexistence required", "error");
          return;
       }
    }
    if (typeof store.config[key] === 'boolean') {
      (store.config as any)[key] = !store.config[key];
    }
  }

  function handleInput(e: Event, key: keyof typeof store.config) {
    const target = e.target as HTMLInputElement;
    (store.config as any)[key] = target.value;
  }
  
  const REPLAY_ICON = "M12 5V1L7 6l5 5V7c3.31 0 6 2.69 6 6s-2.69 6-6 6-6-2.69-6-6H4c0 4.42 3.58 8 8 8s8-3.58 8-8-3.58-8-8-8z";
</script>

<md-dialog 
  open={showResetConfirm} 
  onclose={() => showResetConfirm = false}
  style="--md-dialog-scrim-color: transparent; --md-sys-color-scrim: transparent;"
>
  <div slot="headline">{store.L.config?.resetConfigTitle ?? 'Reset Configuration?'}</div>
  <div slot="content">
    {store.L.config?.resetConfigConfirm ?? 'This will reset all backend settings to defaults. Continue?'}
  </div>
  <div slot="actions">
    <md-text-button 
      onclick={() => showResetConfirm = false}
      role="button"
      tabindex="0"
      onkeydown={() => {}}
    >
      {store.L.common?.cancel ?? 'Cancel'}
    </md-text-button>
    <md-text-button 
      onclick={reset}
      role="button"
      tabindex="0"
      onkeydown={() => {}}
    >
      {store.L.config?.resetConfig ?? 'Reset Config'}
    </md-text-button>
  </div>
</md-dialog>

<div class="config-container">
  <section class="config-group">
    <div class="config-card">
      <div class="card-header">
        <div class="card-icon">
          <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.storage} /></svg></md-icon>
        </div>
        <div class="card-text">
          <span class="card-title">{store.L.status?.storageTitle ?? 'Storage'}</span>
          <span class="card-desc">Configure paths</span>
        </div>
      </div>
      
      <div class="input-stack">
        <md-outlined-text-field 
          label={store.L.config.moduleDir} 
          value={store.config.moduledir}
          oninput={(e) => handleInput(e, 'moduledir')}
          error={invalidModuleDir}
          class="full-width-field"
        >
          <md-icon slot="leading-icon"><svg viewBox="0 0 24 24"><path d={ICONS.modules} /></svg></md-icon>
        </md-outlined-text-field>

        <md-outlined-text-field 
          label={store.L.config.tempDir} 
          value={store.config.tempdir}
          oninput={(e) => handleInput(e, 'tempdir')}
          placeholder={store.L.config.autoPlaceholder}
          error={invalidTempDir}
          class="full-width-field"
        >
          <md-icon slot="leading-icon"><svg viewBox="0 0 24 24"><path d={ICONS.timer} /></svg></md-icon>
          {#if store.config.tempdir}
            <md-icon-button 
                slot="trailing-icon" 
                onclick={resetTempDir}
                role="button"
                tabindex="0"
                onkeydown={() => {}}
            >
              <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.close} /></svg></md-icon>
            </md-icon-button>
          {/if}
        </md-outlined-text-field>
      </div>
    </div>
  </section>

  <section class="config-group">
    <div class="config-card">
      <div class="card-header">
        <div class="card-icon">
          <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.storage} /></svg></md-icon>
        </div>
        <div class="card-text">
          <span class="card-title">{store.L.config.partitions}</span>
          <span class="card-desc">Add partitions to mount</span>
        </div>
      </div>
      <div class="p-input">
        <ChipInput bind:values={store.config.partitions} placeholder="e.g. product, system_ext..." />
      </div>
    </div>
  </section>

  <section class="config-group">
    <div class="options-grid">
      <div class="option-tile static-input">
        <div class="tile-top">
          <div class="tile-icon neutral">
            <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.ksu} /></svg></md-icon>
          </div>
        </div>
        <div class="tile-bottom">
          <span class="tile-label">{store.L.config.mountSource}</span>
          <input class="tile-input-overlay" type="text" bind:value={store.config.mountsource} />
        </div>
      </div>

      <button 
        class="option-tile clickable secondary" 
        class:active={store.config.force_ext4} 
        onclick={() => toggle('force_ext4')}
      >
        <md-ripple></md-ripple>
        <div class="tile-top">
          <div class="tile-icon">
            <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.save} /></svg></md-icon>
          </div>
        </div>
        <div class="tile-bottom">
          <span class="tile-label">{store.L.config.forceExt4}</span>
        </div>
      </button>

      <button 
        class="option-tile clickable error" 
        class:active={store.config.enable_nuke} 
        onclick={() => toggle('enable_nuke')}
      >
        <md-ripple></md-ripple>
        <div class="tile-top">
          <div class="tile-icon">
            <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.cat_paw} /></svg></md-icon>
          </div>
        </div>
        <div class="tile-bottom">
          <span class="tile-label">{store.L.config.enableNuke}</span>
        </div>
      </button>

      <button 
        class="option-tile clickable tertiary" 
        class:active={store.config.disable_umount} 
        onclick={() => toggle('disable_umount')}
      >
        <md-ripple></md-ripple>
        <div class="tile-top">
          <div class="tile-icon">
            <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.anchor} /></svg></md-icon>
          </div>
        </div>
        <div class="tile-bottom">
          <span class="tile-label">{store.L.config.disableUmount}</span>
        </div>
      </button>

      {#if store.systemInfo?.zygisksuEnforce && store.systemInfo.zygisksuEnforce !== '0'}
        <button 
          class="option-tile clickable error" 
          class:active={store.config.allow_umount_coexistence} 
          onclick={() => toggle('allow_umount_coexistence')}
          transition:slide
        >
          <md-ripple></md-ripple>
          <div class="tile-top">
            <div class="tile-icon">
              <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.shield} /></svg></md-icon>
            </div>
          </div>
          <div class="tile-bottom">
              <span class="tile-label">{store.L.config?.allowUmountCoexistence || 'Allow Coexistence'}</span>
          </div>
        </button>
      {/if}

      <button 
        class="option-tile clickable primary" 
        class:active={store.config.verbose} 
        onclick={() => toggle('verbose')}
      >
        <md-ripple></md-ripple>
        <div class="tile-top">
          <div class="tile-icon">
             <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.description} /></svg></md-icon>
          </div>
        </div>
        <div class="tile-bottom">
          <span class="tile-label">{store.L.config.verboseLabel}</span>
        </div>
      </button>

      {#if store.config.verbose}
        <button 
          class="option-tile clickable secondary" 
          class:active={store.config.dry_run} 
          onclick={() => toggle('dry_run')}
          transition:slide
        >
          <md-ripple></md-ripple>
          <div class="tile-top">
            <div class="tile-icon">
              <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.ghost} /></svg></md-icon>
             </div>
          </div>
          <div class="tile-bottom">
            <span class="tile-label">{store.L.config.dryRun}</span>
          </div>
        </button>
      {/if}
    </div>
  </section>

  <section class="config-group">
    <div class="webui-label">
        {store.L.config?.webui || 'WebUI'}
    </div>
    <div class="options-grid">
      <button 
        class="option-tile clickable secondary" 
        class:active={store.fixBottomNav} 
        onclick={store.toggleBottomNavFix}
      >
        <md-ripple></md-ripple>
        <div class="tile-top">
          <div class="tile-icon">
            <md-icon><svg viewBox="0 0 24 24"><path d="M21 5v14H3V5h18zm0-2H3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM8 17h5v-6H8v6zm0-8h5V7H8v2zM6 17h2V7H6v10zm12-6h-2v6h2v-6zm0-4h-2v2h2V7z" /></svg></md-icon>
          </div>
        </div>
        <div class="tile-bottom">
          <span class="tile-label">{store.L.config?.fixBottomNav || 'Fix Bottom Nav'}</span>
        </div>
      </button>

      <button 
        class="option-tile clickable error" 
        onclick={() => showResetConfirm = true}
        disabled={store.saving.config}
      >
        <md-ripple></md-ripple>
        <div class="tile-top">
          <div class="tile-icon">
            <md-icon><svg viewBox="0 0 24 24"><path d={REPLAY_ICON} /></svg></md-icon>
          </div>
        </div>
        <div class="tile-bottom">
          <span class="tile-label">{store.L.config?.resetConfig || 'Reset Config'}</span>
        </div>
      </button>
    </div>
  </section>
</div>

<BottomActions>
  <md-filled-tonal-icon-button 
    onclick={reload}
    disabled={store.loading.config}
    title={store.L.config.reload}
    role="button"
    tabindex="0"
    onkeydown={() => {}}
  >
    <md-icon><svg viewBox="0 0 24 24"><path d={ICONS.refresh} /></svg></md-icon>
  </md-filled-tonal-icon-button>
  
  <div class="spacer"></div>

  <md-filled-button 
    onclick={save} 
    disabled={store.saving.config || !isDirty}
    role="button"
    tabindex="0"
    onkeydown={() => {}}
  >
    <md-icon slot="icon"><svg viewBox="0 0 24 24"><path d={ICONS.save} /></svg></md-icon>
    {store.saving.config ? store.L.common.saving : store.L.config.save}
  </md-filled-button>
</BottomActions>

// webui/src/routes/ConfigTab.tsx
/**
 * Copyright 2026 Hybrid Mount Developers
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { createSignal, createEffect, createMemo, Show, For } from "solid-js";
import { store } from "../lib/store";
import { ICONS } from "../lib/constants";
import { API } from "../lib/api";
import ChipInput from "../components/ChipInput";
import BottomActions from "../components/BottomActions";
import "./ConfigTab.css";
import "@material/web/textfield/outlined-text-field.js";
import "@material/web/button/filled-button.js";
import "@material/web/iconbutton/filled-tonal-icon-button.js";
import "@material/web/iconbutton/icon-button.js";
import "@material/web/icon/icon.js";
import "@material/web/ripple/ripple.js";
import "@material/web/dialog/dialog.js";
import "@material/web/button/text-button.js";
import "@material/web/switch/switch.js";
import type { OverlayMode, AppConfig } from "../lib/types";

export default function ConfigTab() {
  const [initialConfigStr, setInitialConfigStr] = createSignal("");
  const [showResetConfirm, setShowResetConfirm] = createSignal(false);

  const isValidPath = (p: string) => !p || (p.startsWith("/") && p.length > 1);
  const invalidModuleDir = createMemo(
    () => !isValidPath(store.config.moduledir),
  );

  const isDirty = createMemo(() => {
    if (!initialConfigStr()) return false;
    return JSON.stringify(store.config) !== initialConfigStr();
  });

  createEffect(() => {
    if (!store.loading.config && store.config) {
      if (
        !initialConfigStr() ||
        initialConfigStr() === JSON.stringify(store.config)
      ) {
        setInitialConfigStr(JSON.stringify(store.config));
      }
    }
  });

  createEffect(() => {
    if (
      store.systemInfo?.zygisksuEnforce &&
      store.systemInfo.zygisksuEnforce !== "0" &&
      !store.config.allow_umount_coexistence
    ) {
      if (!store.config.disable_umount) {
        updateConfig("disable_umount", true);
      }
    }
  });

  function updateConfig<K extends keyof AppConfig>(
    key: K,
    value: AppConfig[K],
  ) {
    store.config = { ...store.config, [key]: value };
  }

  function save() {
    if (invalidModuleDir()) {
      store.showToast(store.L.config.invalidPath, "error");
      return;
    }
    store.saveConfig().then(() => {
      setInitialConfigStr(JSON.stringify(store.config));
    });
  }

  function reload() {
    store.loadConfig().then(() => {
      setInitialConfigStr(JSON.stringify(store.config));
    });
  }

  function reset() {
    setShowResetConfirm(false);
    store.resetConfig().then(() => {
      setInitialConfigStr(JSON.stringify(store.config));
    });
  }

  function toggle(key: keyof AppConfig) {
    const currentVal = store.config[key] as boolean;
    const newVal = !currentVal;

    if (key === "disable_umount") {
      if (
        store.systemInfo?.zygisksuEnforce &&
        store.systemInfo.zygisksuEnforce !== "0" &&
        !store.config.allow_umount_coexistence
      ) {
        store.showToast(
          store.L.config?.coexistenceRequired || "Coexistence required",
          "error",
        );
        return;
      }
    }

    updateConfig(key, newVal);

    API.saveConfig({ ...store.config, [key]: newVal }).catch(() => {
      updateConfig(key, currentVal);
      store.showToast(
        store.L.config?.saveFailed || "Failed to update setting",
        "error",
      );
    });
  }

  function setOverlayMode(mode: string) {
    updateConfig("overlay_mode", mode as OverlayMode);
  }

  const availableModes = createMemo(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const storageModes = (store.storage as any)?.supported_modes;
    let modes: OverlayMode[];

    if (storageModes && Array.isArray(storageModes)) {
      modes = storageModes as OverlayMode[];
    } else {
      modes =
        store.systemInfo?.supported_overlay_modes ??
        (["tmpfs", "ext4", "erofs"] as OverlayMode[]);
    }

    if (store.systemInfo?.tmpfs_xattr_supported === false) {
      modes = modes.filter((m) => m !== "tmpfs");
    }

    return modes;
  });

  const MODE_DESCS: Record<OverlayMode, string> = {
    tmpfs: "RAM-based. Fastest I/O, reset on reboot.",
    ext4: "Loopback image. Persistent, saves RAM.",
    erofs: "Read-only compressed. High performance, space saving.",
  };

  return (
    <>
      <md-dialog
        open={showResetConfirm()}
        onclose={() => setShowResetConfirm(false)}
        class="transparent-scrim"
      >
        <div slot="headline">
          {store.L.config?.resetConfigTitle ?? "Reset Configuration?"}
        </div>
        <div slot="content">
          {store.L.config?.resetConfigConfirm ??
            "This will reset all backend settings to defaults. Continue?"}
        </div>
        <div slot="actions">
          <md-text-button onClick={() => setShowResetConfirm(false)}>
            {store.L.common?.cancel ?? "Cancel"}
          </md-text-button>
          <md-text-button onClick={reset}>
            {store.L.config?.resetConfig ?? "Reset Config"}
          </md-text-button>
        </div>
      </md-dialog>

      <div class="config-container">
        <section class="config-group">
          <div class="config-card">
            <div class="card-header">
              <div class="card-icon">
                <md-icon>
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.modules} />
                  </svg>
                </md-icon>
              </div>
              <div class="card-text">
                <span class="card-title">{store.L.config.moduleDir}</span>
                <span class="card-desc">
                  {store.L.config?.moduleDirDesc ??
                    "Set the directory where modules are stored"}
                </span>
              </div>
            </div>

            <div class="input-stack">
              <md-outlined-text-field
                label={store.L.config.moduleDir}
                value={store.config.moduledir}
                onInput={(e: Event) =>
                  updateConfig(
                    "moduledir",
                    (e.currentTarget as HTMLInputElement).value,
                  )
                }
                error={invalidModuleDir()}
                supporting-text={
                  invalidModuleDir()
                    ? store.L.config?.invalidModuleDir || "Invalid Path"
                    : ""
                }
                class="full-width-field"
              >
                <md-icon slot="leading-icon">
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.modules} />
                  </svg>
                </md-icon>
              </md-outlined-text-field>
            </div>
          </div>

          <div class="config-card">
            <div class="card-header">
              <div class="card-icon">
                <md-icon>
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.ksu} />
                  </svg>
                </md-icon>
              </div>
              <div class="card-text">
                <span class="card-title">{store.L.config.mountSource}</span>
                <span class="card-desc">
                  {store.L.config?.mountSourceDesc ??
                    "Global mount source namespace (e.g. KSU)"}
                </span>
              </div>
            </div>

            <div class="input-stack">
              <md-outlined-text-field
                label={store.L.config.mountSource}
                value={store.config.mountsource}
                onInput={(e: Event) =>
                  updateConfig(
                    "mountsource",
                    (e.currentTarget as HTMLInputElement).value,
                  )
                }
                class="full-width-field"
              >
                <md-icon slot="leading-icon">
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.ksu} />
                  </svg>
                </md-icon>
              </md-outlined-text-field>
            </div>
          </div>

          <div class="config-card">
            <div class="card-header">
              <div class="card-icon">
                <md-icon>
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.mount_path} />
                  </svg>
                </md-icon>
              </div>
              <div class="card-text">
                <span class="card-title">
                  {store.L.config?.hybrid_mnt_dir ?? "Mount Point Path"}
                </span>
                <span class="card-desc">
                  {store.L.config?.hybrid_mnt_dir_desc ??
                    "Temporary directory for OverlayFS mounting"}
                </span>
              </div>
            </div>

            <div class="input-stack">
              <md-outlined-text-field
                label={store.L.config?.hybrid_mnt_dir ?? "Mount Point Path"}
                value={store.config.hybrid_mnt_dir ?? ""}
                onInput={(e: Event) =>
                  updateConfig(
                    "hybrid_mnt_dir",
                    (e.currentTarget as HTMLInputElement).value,
                  )
                }
                class="full-width-field"
              >
                <md-icon slot="leading-icon">
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.mount_path} />
                  </svg>
                </md-icon>
              </md-outlined-text-field>
            </div>
          </div>
        </section>

        <section class="config-group">
          <div class="config-card">
            <div class="card-header">
              <div class="card-icon">
                <md-icon>
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.storage} />
                  </svg>
                </md-icon>
              </div>
              <div class="card-text">
                <span class="card-title">{store.L.config.partitions}</span>
                <span class="card-desc">
                  {store.L.config?.partitionsDesc ?? "Add partitions to mount"}
                </span>
              </div>
            </div>
            <div class="p-input">
              <ChipInput
                values={store.config.partitions}
                placeholder="e.g. product, system_ext..."
                onValuesChange={(vals) => updateConfig("partitions", vals)}
              />
            </div>
          </div>
        </section>

        <section class="config-group">
          <div class="config-card">
            <div class="card-header">
              <div class="card-icon">
                <md-icon>
                  <svg viewBox="0 0 24 24">
                    <path d={ICONS.save} />
                  </svg>
                </md-icon>
              </div>
              <div class="card-text">
                <span class="card-title">
                  {store.L.config?.overlayMode || "Overlay Mode"}
                </span>
                <span class="card-desc">
                  {store.L.config?.overlayModeDesc ||
                    "Select backing storage strategy"}
                </span>
              </div>
            </div>
            <div class="mode-selector">
              <For each={availableModes()}>
                {(mode) => (
                  <button
                    class={`mode-item ${store.config.overlay_mode === mode ? "selected" : ""}`}
                    onClick={() => setOverlayMode(mode)}
                  >
                    <md-ripple></md-ripple>
                    <div class="mode-info">
                      <span class="mode-title">
                        {store.L.config?.[`mode_${mode}`] || mode}
                      </span>
                      <span class="mode-desc">
                        {store.L.config?.[`mode_${mode}Desc`] ||
                          MODE_DESCS[mode]}
                      </span>
                    </div>
                    <div class="mode-check">
                      <md-icon>
                        <svg viewBox="0 0 24 24">
                          <path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" />
                        </svg>
                      </md-icon>
                    </div>
                  </button>
                )}
              </For>
            </div>
          </div>

          <div class="options-grid">
            <button
              class={`option-tile clickable tertiary ${store.config.disable_umount ? "active" : ""}`}
              onClick={() => toggle("disable_umount")}
            >
              <md-ripple></md-ripple>
              <div class="tile-top">
                <div class="tile-icon">
                  <md-icon>
                    <svg viewBox="0 0 24 24">
                      <path d={ICONS.anchor} />
                    </svg>
                  </md-icon>
                </div>
              </div>
              <div class="tile-bottom">
                <span class="tile-label">{store.L.config.disableUmount}</span>
              </div>
            </button>

            <Show
              when={
                store.systemInfo?.zygisksuEnforce &&
                store.systemInfo.zygisksuEnforce !== "0"
              }
            >
              <button
                class={`option-tile clickable error ${store.config.allow_umount_coexistence ? "active" : ""}`}
                onClick={() => toggle("allow_umount_coexistence")}
              >
                <md-ripple></md-ripple>
                <div class="tile-top">
                  <div class="tile-icon">
                    <md-icon>
                      <svg viewBox="0 0 24 24">
                        <path d={ICONS.shield} />
                      </svg>
                    </md-icon>
                  </div>
                </div>
                <div class="tile-bottom">
                  <span class="tile-label">
                    {store.L.config?.allowUmountCoexistence ||
                      "Allow Coexistence"}
                  </span>
                </div>
              </button>
            </Show>
          </div>
        </section>

        <section class="config-group">
          <div class="webui-label">{store.L.config?.webui || "WebUI"}</div>
          <div class="options-grid">
            <button
              class={`option-tile clickable secondary ${store.fixBottomNav ? "active" : ""}`}
              onClick={store.toggleBottomNavFix}
            >
              <md-ripple></md-ripple>
              <div class="tile-top">
                <div class="tile-icon">
                  <md-icon>
                    <svg viewBox="0 0 24 24">
                      <path d="M21 5v14H3V5h18zm0-2H3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM8 17h5v-6H8v6zm0-8h5V7H8v2zM6 17h2V7H6v10zm12-6h-2v6h2v-6zm0-4h-2v2h2V7z" />
                    </svg>
                  </md-icon>
                </div>
              </div>
              <div class="tile-bottom">
                <span class="tile-label">
                  {store.L.config?.fixBottomNav || "Fix Bottom Nav"}
                </span>
              </div>
            </button>

            <button
              class="option-tile clickable error"
              onClick={() => setShowResetConfirm(true)}
              disabled={store.saving.config}
            >
              <md-ripple></md-ripple>
              <div class="tile-top">
                <div class="tile-icon">
                  <md-icon>
                    <svg viewBox="0 0 24 24">
                      <path d={ICONS.replay} />
                    </svg>
                  </md-icon>
                </div>
              </div>
              <div class="tile-bottom">
                <span class="tile-label">
                  {store.L.config?.resetConfig || "Reset Config"}
                </span>
              </div>
            </button>
          </div>
        </section>
      </div>

      <BottomActions>
        <md-filled-tonal-icon-button
          onClick={reload}
          disabled={store.loading.config}
          title={store.L.config.reload}
          role="button"
          tabIndex={0}
        >
          <md-icon>
            <svg viewBox="0 0 24 24">
              <path d={ICONS.refresh} />
            </svg>
          </md-icon>
        </md-filled-tonal-icon-button>

        <div class="spacer"></div>

        <md-filled-button
          onClick={save}
          disabled={store.saving.config || !isDirty()}
          role="button"
          tabIndex={0}
        >
          <md-icon slot="icon">
            <svg viewBox="0 0 24 24">
              <path d={ICONS.save} />
            </svg>
          </md-icon>
          {store.saving.config ? store.L.common.saving : store.L.config.save}
        </md-filled-button>
      </BottomActions>
    </>
  );
}
